#!/bin/sh

rm -rf gen-*
docker run -v "$PWD:/data" index.alauda.cn/zhangheng/red:thrift thrift -r -o /data/thrift --gen java /data/thrift/netSDK.thrift
docker run -v "$PWD:/data" index.alauda.cn/zhangheng/red:thrift thrift -r -o /data/thrift --gen cpp  /data/thrift/netSDK.thrift

docker run -v "$PWD:/build" -w /build/cpp index.alauda.cn/zhangheng/red:cppbuild make  x64 PLAT=64

docker run -v "$PWD:/build" -w /build/clojure index.alauda.cn/zhangheng/red:cljbuild lein uberjar

docker build -t index.alauda.cn/zhangheng/red .
